# Generated by Django 5.0.8 on 2024-08-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_assigned_to_task_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_edit_task', 'Can edit task'), ('can_delete_task', 'Can delete task')]},
        ),
    ]
